### ISSUE TITLE
ObjectSkills not shown in the SkillComponent

### ISSUE THREAD

**Issue by SimonNitzsche** [Xiphoseer/lu-explorer#24] opened 2020-12-27 01:54 UTC
Example for stromlings: https://lu-explorer.web.app/objects/4712/9

**Comment by Xiphoseer** [comment] 2021-01-06 15:52
Fixed in the latest deploy. (This doesn't apply to some other skills where the issue is that the JSON is `null`)

**Closed by Xiphoseer** 2021-01-06 15:52 UTC
